# Generated by Django 2.2.1 on 2019-05-29 06:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Dealer'), (1, 'API Customer')], default=0)),
                ('payment_policy', models.PositiveSmallIntegerField(choices=[(0, 'Prepaid'), (1, 'Post-paid'), (2, 'Direct Payment')])),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limit_hotel', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('commission_pct', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0)),
                ('can_create_sub_dealer', models.BooleanField(default=False, verbose_name='Can Create Sub-dealer?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='agent.Agent')),
            ],
            options={
                'verbose_name': 'Agent',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Reject')], default=0)),
                ('payment_mode', models.IntegerField(choices=[(0, 'Cash'), (1, 'bKash'), (2, 'CreditCard'), (3, 'Cheque')], default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.Agent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_top_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_top_ups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
